export enum WarFrequency {
  UNKNOWN = 'UNKNOWN',
  ALWAYS = 'ALWAYS',
  MORE_THAN_ONCE_PER_WEEK = 'MORE_THAN_ONCE_PER_WEEK',
  ONCE_PER_WEEK = 'ONCE_PER_WEEK',
  LESS_THAN_ONCE_PER_WEEK = 'LESS_THAN_ONCE_PER_WEEK',
  NEVER = 'NEVER',
  ANY = 'ANY'
}